/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Create a new git worktree with a new branch.
 *
 * The worktree is placed at `<repo_path>/../<worktree_name>` by convention,
 * and a new branch `branch_name` is created pointing at the current HEAD.
 */
export declare function createWorktree(repoPath: string, worktreeName: string, branchName: string): WorktreeInfo

/** Get repository information including current branch, remote URL, dirty state, and HEAD commit. */
export declare function getRepoInfo(path: string): RepoInfo

/** Get a unified diff of all changes (staged + unstaged + untracked) in a worktree. */
export declare function getWorktreeDiff(worktreePath: string): string

/** Health check function to verify the native module is loaded correctly. */
export declare function healthCheck(): string

/** List all worktrees for a repository. */
export declare function listWorktrees(repoPath: string): Array<WorktreeInfo>

/** Returns the version of the native module. */
export declare function nativeVersion(): string

/** Remove a git worktree. If `force` is true, removes even with uncommitted changes. */
export declare function removeWorktree(repoPath: string, worktreeName: string, force: boolean): boolean

/** Information about a git repository. */
export interface RepoInfo {
  /** Name of the current branch (e.g. "main"). */
  currentBranch: string
  /** Remote URL if configured (e.g. "https://github.com/user/repo.git"). */
  remoteUrl?: string
  /** Whether the working directory has uncommitted changes. */
  isDirty: boolean
  /** SHA of the HEAD commit. */
  headCommitSha: string
  /** First line of the HEAD commit message. */
  headCommitMessage: string
}

/** Check if a worktree (or any repo working directory) has uncommitted changes. */
export declare function worktreeHasChanges(worktreePath: string): boolean

/** Information about a git worktree. */
export interface WorktreeInfo {
  /** Name of the worktree. */
  name: string
  /** Absolute filesystem path of the worktree. */
  path: string
  /** Branch the worktree is checked out on. */
  branch: string
  /** Whether this is the bare/main worktree. */
  isBare: boolean
}

// ─── Diff types (T28) ──────────────────────────────────────────────────────

/** A single line in a diff hunk. */
export interface DiffLine {
  /** Line content (without leading +/-/ prefix). */
  content: string
  /** Line type: "addition", "deletion", or "context". */
  lineType: string
  /** Line number in the old file (null for additions). */
  oldLineno?: number
  /** Line number in the new file (null for deletions). */
  newLineno?: number
}

/** A contiguous section of changes within a file. */
export interface DiffHunk {
  /** Starting line number in the old file. */
  oldStart: number
  /** Number of lines in the old file. */
  oldLines: number
  /** Starting line number in the new file. */
  newStart: number
  /** Number of lines in the new file. */
  newLines: number
  /** Optional hunk header text (e.g. function name). */
  header: string
  /** Lines in this hunk. */
  lines: Array<DiffLine>
}

/** A file that has changes. */
export interface FileDiff {
  /** File path (new path for renames/additions, old path for deletions). */
  path: string
  /** Old file path (for renames). */
  oldPath?: string
  /** File status: "added", "modified", "deleted", "renamed". */
  status: string
  /** Whether this is a binary file. */
  binary: boolean
  /** Diff hunks for this file. */
  hunks: Array<DiffHunk>
}

/** Get structured diff of changes (staged or unstaged). */
export declare function getDiff(repoPath: string, staged: boolean): Array<FileDiff>

// ─── Oplog types (T29) ─────────────────────────────────────────────────────

/** A snapshot of the repo state at a point in time. */
export interface RepoSnapshot {
  /** HEAD commit SHA. */
  headSha: string
  /** Current branch name. */
  branch: string
  /** Timestamp (unix seconds). */
  timestamp: number
}

/** Get the current repo snapshot (HEAD sha + branch + timestamp). */
export declare function getRepoSnapshot(repoPath: string): RepoSnapshot

/** Revert to a specific commit by creating a new commit that restores its tree. */
export declare function revertToSnapshot(repoPath: string, targetSha: string): string
