/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Persistent state for an agent's output stream.
 * Holds the incomplete line buffer between chunks.
 */
export declare class AgentOutputStream {
  /**
   * Create a new output stream for an agent.
   * `resume_command_pattern`: substring prefix from provider config (e.g. "claude --resume ").
   * Pass empty string when the provider has no resume support.
   */
  constructor(cliType: string, resumeCommandPattern: string)
  /**
   * Process a chunk of raw PTY output.
   * Returns cleaned text + optional status update.
   */
  processChunk(rawData: string): ProcessedOutput
  /** Reset the buffer (e.g., on agent restart). */
  reset(): void
}

/**
 * Create a new git worktree with a new branch.
 *
 * If `target_path` is provided, the worktree is placed there.
 * Otherwise falls back to `<repo_path>/../<worktree_name>`.
 * A new branch `branch_name` is created pointing at the current HEAD.
 */
export declare function createWorktree(repoPath: string, worktreeName: string, branchName: string, targetPath?: string | undefined | null): WorktreeInfo

/** A contiguous section of changes within a file. */
export interface DiffHunk {
  /** Starting line number in the old file. */
  oldStart: number
  /** Number of lines in the old file. */
  oldLines: number
  /** Starting line number in the new file. */
  newStart: number
  /** Number of lines in the new file. */
  newLines: number
  /** Optional hunk header text (e.g. function name). */
  header: string
  /** Lines in this hunk. */
  lines: Array<DiffLine>
}

/** A single line in a diff hunk. */
export interface DiffLine {
  /** Line content (without leading +/-/ prefix). */
  content: string
  /** Line type: "addition", "deletion", or "context". */
  lineType: string
  /** Line number in the old file (null for additions). */
  oldLineno?: number
  /** Line number in the new file (null for deletions). */
  newLineno?: number
}

/** A file that has changes. */
export interface FileDiff {
  /** File path (new path for renames/additions, old path for deletions). */
  path: string
  /** Old file path (for renames). */
  oldPath?: string
  /** File status: "added", "modified", "deleted", "renamed". */
  status: string
  /** Whether this is a binary file. */
  binary: boolean
  /** Diff hunks for this file. */
  hunks: Array<DiffHunk>
}

/**
 * Get structured diff of changes (staged or unstaged).
 * Returns a list of FileDiff objects with hunks and lines.
 */
export declare function getDiff(repoPath: string, staged: boolean): Array<FileDiff>

/** Get repository information including current branch, remote URL, dirty state, and HEAD commit. */
export declare function getRepoInfo(path: string): RepoInfo

/** Get the current repo snapshot (HEAD sha + branch + timestamp). */
export declare function getRepoSnapshot(repoPath: string): RepoSnapshot

/** Get a unified diff of all changes (staged + unstaged + untracked) in a worktree. */
export declare function getWorktreeDiff(worktreePath: string): string

/** Health check function to verify the native module is loaded correctly. */
export declare function healthCheck(): string

/** List all worktrees for a repository. */
export declare function listWorktrees(repoPath: string): Array<WorktreeInfo>

/** Returns the version of the native module. */
export declare function nativeVersion(): string

/** Result of processing a chunk of PTY output. */
export interface ProcessedOutput {
  /** Cleaned lines (ANSI stripped, CR removed) — for scrollback storage. */
  cleanText: string
  /** Status update if a meaningful pattern was detected. */
  status?: string
  /** Current step/tool being executed. */
  currentStep?: string
  /** Whether a token limit warning was detected. */
  tokenLimitWarning: boolean
  /** Claude session ID parsed from startup output (T101, kept for backwards compat). */
  sessionId?: string
  /**
   * Full resume command extracted from agent shutdown output (T101).
   * e.g. "claude --resume <id>", "gemini --resume <id>", "opencode -s <id>",
   *      "codex resume <id>", "droid --resume <id>"
   */
  resumeCommand?: string
}

/** Remove a git worktree. If `force` is true, removes even with uncommitted changes. */
export declare function removeWorktree(repoPath: string, worktreeName: string, force: boolean): boolean

/** Information about a git repository. */
export interface RepoInfo {
  /** Name of the current branch (e.g. "main"). */
  currentBranch: string
  /** Remote URL if configured (e.g. "https://github.com/user/repo.git"). */
  remoteUrl?: string
  /** Whether the working directory has uncommitted changes. */
  isDirty: boolean
  /** SHA of the HEAD commit. */
  headCommitSha: string
  /** First line of the HEAD commit message. */
  headCommitMessage: string
}

/** A snapshot of the repo state at a point in time. */
export interface RepoSnapshot {
  /** HEAD commit SHA. */
  headSha: string
  /** Current branch name. */
  branch: string
  /** Timestamp (unix seconds). */
  timestamp: number
}

/**
 * Revert to a specific commit by creating a new commit that restores its tree.
 * Never force-pushes — creates a new "revert" commit on current branch.
 */
export declare function revertToSnapshot(repoPath: string, targetSha: string): string

/**
 * Strip ANSI escape codes from terminal output.
 * 50-100x faster than JS regex replacement.
 *
 * Handles:
 * - CSI sequences: ESC [ ... final_byte (colors, cursor, etc.)
 * - OSC sequences: ESC ] ... ST (title, hyperlinks)
 * - Simple escapes: ESC followed by single char (ESC D, ESC M, etc.)
 * - Synchronized output: ESC [ ? 2026 h/l
 */
export declare function stripAnsi(input: string): string

/** Check if a worktree (or any repo working directory) has uncommitted changes. */
export declare function worktreeHasChanges(worktreePath: string): boolean

/** Information about a git worktree. */
export interface WorktreeInfo {
  /** Name of the worktree. */
  name: string
  /** Absolute filesystem path of the worktree. */
  path: string
  /** Branch the worktree is checked out on. */
  branch: string
  /** Whether this is the bare/main worktree. */
  isBare: boolean
}
