/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Persistent state for an agent's output stream.
 * Holds the incomplete line buffer between chunks.
 */
export declare class AgentOutputStream {
  /**
   * Create a new output stream for an agent.
   * `resume_command_pattern`: substring prefix from provider config (e.g. "claude --resume ").
   * Pass empty string when the provider has no resume support.
   */
  constructor(cliType: string, resumeCommandPattern: string)
  /**
   * Process a chunk of raw PTY output.
   * Returns cleaned text + optional status update.
   */
  processChunk(rawData: string): ProcessedOutput
  /** Reset the buffer (e.g., on agent restart). */
  reset(): void
}

/**
 * Commit a previously prepared tree onto the hidden oplog chain
 * (`commit_snapshot` half of the unmaterialized pattern) — call this only
 * when the agent turn actually succeeded; on failure, simply discard the
 * prepared snapshot and nothing is ever written to the chain.
 */
export declare function commitTurnSnapshot(repoPath: string, treeSha: string, operation: string, agentId: string, provider: string, turnIndex: number, description: string): OplogSnapshotInfo

/**
 * Create a new git worktree with a new branch.
 *
 * If `target_path` is provided, the worktree is placed there.
 * Otherwise falls back to `<repo_path>/../<worktree_name>`.
 * A new branch `branch_name` is created pointing at the current HEAD.
 */
export declare function createWorktree(repoPath: string, worktreeName: string, branchName: string, targetPath?: string | undefined | null): WorktreeInfo

/** A contiguous section of changes within a file. */
export interface DiffHunk {
  /** Starting line number in the old file. */
  oldStart: number
  /** Number of lines in the old file. */
  oldLines: number
  /** Starting line number in the new file. */
  newStart: number
  /** Number of lines in the new file. */
  newLines: number
  /** Optional hunk header text (e.g. function name). */
  header: string
  /** Lines in this hunk. */
  lines: Array<DiffLine>
}

/** A single line in a diff hunk. */
export interface DiffLine {
  /** Line content (without leading +/-/ prefix). */
  content: string
  /** Line type: "addition", "deletion", or "context". */
  lineType: string
  /** Line number in the old file (null for additions). */
  oldLineno?: number
  /** Line number in the new file (null for deletions). */
  newLineno?: number
}

/** A file that has changes. */
export interface FileDiff {
  /** File path (new path for renames/additions, old path for deletions). */
  path: string
  /** Old file path (for renames). */
  oldPath?: string
  /** File status: "added", "modified", "deleted", "renamed". */
  status: string
  /** Whether this is a binary file. */
  binary: boolean
  /** Diff hunks for this file. */
  hunks: Array<DiffHunk>
}

/**
 * Regex-search file contents under `root`. Gitignore-aware by default,
 * honors `globs` include filters, skips files larger than
 * `max_file_size_kb`, stops early once `max_matches` is reached.
 *
 * `root` MUST be a directory the caller is authorized to search; this
 * function does no path validation. Returns Err on invalid regex or
 * missing root.
 */
export declare function fsGrep(pattern: string, root: string, opts: GrepOptions): Array<GrepHit>

/**
 * Fuzzy-find files and directories under `root`.
 *
 * `root` MUST be a directory the caller is authorized to search; this
 * function does no path validation. Results are gitignore-aware (default)
 * and bounded by `max_results`.
 *
 * Scoring: basename substring (+200) outranks full-path substring (+100);
 * word-boundary hits add +50; subsequence-only matches score by query
 * length. Empty query returns the first `max_results` entries in walk order.
 */
export declare function fsSearch(query: string, root: string, limits: SearchLimits): Array<SearchResult>

/**
 * Get structured diff of changes (staged or unstaged).
 * Returns a list of FileDiff objects with hunks and lines.
 */
export declare function getDiff(repoPath: string, staged: boolean): Array<FileDiff>

/** Get repository information including current branch, remote URL, dirty state, and HEAD commit. */
export declare function getRepoInfo(path: string): RepoInfo

/** Get the current repo snapshot (HEAD sha + branch + timestamp). */
export declare function getRepoSnapshot(repoPath: string): RepoSnapshot

/** Get a unified diff of all changes (staged + unstaged + untracked) in a worktree. */
export declare function getWorktreeDiff(worktreePath: string): string

/** A single line match from `fs_grep`. */
export interface GrepHit {
  /** Absolute path on disk. */
  path: string
  /** Path relative to the search `root` (forward-slash form). */
  relativePath: string
  /** 1-indexed line number where the match was found. */
  lineNumber: number
  /** The matching line content (trailing newline stripped, truncated to ~240 chars). */
  line: string
  /**
   * 0-indexed BYTE offset of the first match in the line (NOT a character column).
   * Renderers using character-column APIs (Monaco, xterm) must convert.
   */
  byteStart: number
  /** 0-indexed BYTE offset (exclusive) of the end of the first match in the line. */
  byteEnd: number
}

/** Options for `fs_grep`. */
export interface GrepOptions {
  /** Case-insensitive regex. Default false. */
  caseInsensitive?: boolean
  /** Include dotfiles. Default false. */
  includeHidden?: boolean
  /** Honor `.gitignore` / `.ignore` / `.git/info/exclude`. Default true. */
  respectGitignore?: boolean
  /** Max matches to return. Default 500, hard cap 5000. */
  maxMatches?: number
  /** Skip files larger than this (KB). Default 1024, hard cap 10240. */
  maxFileSizeKb?: number
  /** Optional include globs (e.g. `["**\/*.ts", "**\/*.tsx"]`). */
  globs?: Array<string>
}

/** Health check function to verify the native module is loaded correctly. */
export declare function healthCheck(): string

/** Walk the hidden oplog chain from its tip, most recent first. */
export declare function listOplogSnapshots(repoPath: string, limit: number): Array<OplogSnapshotInfo>

/** List all worktrees for a repository. */
export declare function listWorktrees(repoPath: string): Array<WorktreeInfo>

/** Returns the version of the native module. */
export declare function nativeVersion(): string

/** A committed turn snapshot in the hidden oplog chain (`refs/exegol/oplog`). */
export interface OplogSnapshotInfo {
  /** Commit SHA of this snapshot. */
  sha: string
  /** Parent snapshot SHA in the chain, if any. */
  parentSha?: string
  /** Trailer: operation kind (e.g. "AgentTurn", "PipelineStep", "Promote"). */
  operation: string
  /** Trailer: agent id that produced this turn. */
  agentId: string
  /** Trailer: CLI provider (e.g. "claude-code", "codex"). */
  provider: string
  /** Trailer: 0-based turn index for this agent. */
  turnIndex: number
  /** Free-text description (commit body, after trailers). */
  description: string
  /** Commit timestamp (unix seconds). */
  timestamp: number
}

/**
 * An in-memory tree built from the current index + worktree, not yet
 * committed. `commit_turn_snapshot` only writes it to the hidden ref chain
 * if the caller's operation actually succeeded (unmaterialized pattern).
 */
export interface PreparedTurnSnapshot {
  /** SHA of the tree object already written to the odb. */
  treeSha: string
  /** SHA of the current tip of the hidden oplog chain, if any. */
  parentSha?: string
}

/**
 * Build a tree from the current index + worktree without persisting
 * anything to disk (`prepare_snapshot` half of the unmaterialized pattern).
 * `index.add_all`/`update_all` mutate only the in-memory `Index` handle —
 * the real `.git/index` file is untouched unless `index.write()` is called,
 * which we deliberately never do here.
 */
export declare function prepareTurnSnapshot(repoPath: string): PreparedTurnSnapshot

/** Result of processing a chunk of PTY output. */
export interface ProcessedOutput {
  /** Cleaned lines (ANSI stripped, CR removed) — for scrollback storage. */
  cleanText: string
  /** Status update if a meaningful pattern was detected. */
  status?: string
  /** Current step/tool being executed. */
  currentStep?: string
  /** Whether a token limit warning was detected. */
  tokenLimitWarning: boolean
  /** Claude session ID parsed from startup output (T101, kept for backwards compat). */
  sessionId?: string
  /**
   * Full resume command extracted from agent shutdown output (T101).
   * e.g. "claude --resume <id>", "gemini --resume <id>", "opencode -s <id>",
   *      "codex resume <id>", "droid --resume <id>"
   */
  resumeCommand?: string
}

/** Remove a git worktree. If `force` is true, removes even with uncommitted changes. */
export declare function removeWorktree(repoPath: string, worktreeName: string, force: boolean): boolean

/** Information about a git repository. */
export interface RepoInfo {
  /** Name of the current branch (e.g. "main"). */
  currentBranch: string
  /** Remote URL if configured (e.g. "https://github.com/user/repo.git"). */
  remoteUrl?: string
  /** Whether the working directory has uncommitted changes. */
  isDirty: boolean
  /** SHA of the HEAD commit. */
  headCommitSha: string
  /** First line of the HEAD commit message. */
  headCommitMessage: string
}

/** A snapshot of the repo state at a point in time. */
export interface RepoSnapshot {
  /** HEAD commit SHA. */
  headSha: string
  /** Current branch name. */
  branch: string
  /** Timestamp (unix seconds). */
  timestamp: number
}

/**
 * Restore working directory + a new HEAD commit to a snapshot's tree.
 * Reuses the same "never force-push, always create a new commit" semantics
 * as `revert_to_snapshot` — the snapshot's tree is resolvable by SHA
 * regardless of hidden-ref reachability once committed to the odb.
 */
export declare function restoreOplogSnapshot(repoPath: string, sha: string): string

/**
 * Revert to a specific commit by creating a new commit that restores its tree.
 * Never force-pushes — creates a new "revert" commit on current branch.
 */
export declare function revertToSnapshot(repoPath: string, targetSha: string): string

/** Limits applied to `fs_search` walks. */
export interface SearchLimits {
  /** Max results to return. Default 100, hard cap 500. */
  maxResults?: number
  /** Max recursion depth. Default 16, hard cap 32. */
  maxDepth?: number
  /** Include dotfiles. Default false. */
  includeHidden?: boolean
  /** Honor `.gitignore` / `.ignore` / `.git/info/exclude`. Default true. */
  respectGitignore?: boolean
}

/** A filename/path hit from `fs_search`. */
export interface SearchResult {
  /** Absolute path on disk. */
  path: string
  /** Path relative to the search `root` (forward-slash form). */
  relativePath: string
  /** Fuzzy match score (higher = better). */
  score: number
  /** True if the entry is a directory. */
  isDir: boolean
}

/**
 * Strip ANSI escape codes from terminal output.
 * 50-100x faster than JS regex replacement.
 *
 * Handles:
 * - CSI sequences: ESC [ ... final_byte (colors, cursor, etc.)
 * - OSC sequences: ESC ] ... ST (title, hyperlinks)
 * - Simple escapes: ESC followed by single char (ESC D, ESC M, etc.)
 * - Synchronized output: ESC [ ? 2026 h/l
 */
export declare function stripAnsi(input: string): string

/** Check if a worktree (or any repo working directory) has uncommitted changes. */
export declare function worktreeHasChanges(worktreePath: string): boolean

/** Information about a git worktree. */
export interface WorktreeInfo {
  /** Name of the worktree. */
  name: string
  /** Absolute filesystem path of the worktree. */
  path: string
  /** Branch the worktree is checked out on. */
  branch: string
  /** Whether this is the bare/main worktree. */
  isBare: boolean
}
